<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Nimbleloop_AiBusinessAnaylst_WebApp-ddd86c40-d0d5-4a29-a032-0cd9f862a73e</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic.SDK" Version="5.10.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="OpenAI" Version="2.9.1" />
    <ProjectReference Include="..\Nimbleloop.AiBusinessAnaylst.WebApp.Client\Nimbleloop.AiBusinessAnaylst.WebApp.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5" />
  </ItemGroup>

</Project>
